name: swiftwash_admin
description: SwiftWash Admin App for managing stores and operators
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  lottie: ^2.4.0
  connectivity_plus: ^4.0.1
  permission_handler: ^10.4.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.1
  flutter_local_notifications: ^15.1.0+1
  fluttertoast: ^8.2.2
  http: ^1.1.0
  dio: ^5.3.2
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^3.0.7
  crypto: ^3.0.3
  encrypt: ^5.0.1
  local_auth: ^2.1.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  share_plus: ^7.2.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.2
  app_settings: ^5.0.0
  flutter_email_sender: ^6.0.2
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^22.2.9
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9
  file_picker: ^5.3.3
  open_file: ^3.3.2
  excel: ^2.1.0
  pdf: ^3.10.4
  printing: ^5.11.1
  screenshot: ^2.1.0
  signature: ^5.3.0
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  skeleton_text: ^3.0.0
  pull_to_refresh: ^2.0.0
  liquid_pull_to_refresh: ^3.0.0
  expandable: ^5.0.1
  readmore: ^2.2.0
  dotted_border: ^2.0.0
  badges: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  animate_do: ^3.1.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
